LicenseManager.Server/Controllers/AdminController.cs
using System.Linq;
using System.Threading.Tasks;
using LicenseManager.Server.Areas.Identity.Data;
using LicenseManager.Server.Data;
using LicenseManager.Server.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Syncfusion.EJ2.Base;

namespace LicenseManager.Server.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext dbContext;
        private readonly UserManager<ApplicationUser> userManager;

        public AdminController(ApplicationDbContext dbContext, UserManager<ApplicationUser> userManager)
        {
            this.dbContext = dbContext;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> UrlDatasource([FromBody] DataManagerRequest dm)
        {
            var adminsList = (await dbContext.Users
                .AsNoTracking()
                .Include(u => u.Licenses)
                .ToListAsync())
                .Where(u => IsAdmin(u).Result);

            var gridObjects = adminsList
                .Select(user => new
                {
                    user.Id,
                    user.UserName,
                    user.Email,
                    user.LockoutEnd,
                    Keys = user.Licenses.Count,
                    user.RegisterDate
                });

            return this.PerformGridOerations(gridObjects, dm);
        }

        private async Task<bool> IsAdmin(ApplicationUser user)
        {
            return await userManager.IsInRoleAsync(user, "Administrator");
        }

        public async Task<IActionResult> Delete([FromBody] CRUDModel<ApplicationUser> crud)
        {
            var user = await userManager.FindByIdAsync(crud.Key.ToString());

            if (await userManager.IsInRoleAsync(user, "SuperAdmin"))
            {
                return StatusCode(400, "SuperAdmin cannot be deleted.");
            }

            await userManager.RemoveFromRoleAsync(user, "Administrator");

            return Json(crud.Value);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            ViewBag.Users = (await dbContext.Users
                .AsNoTracking()
                .ToListAsync())
                .Where(u => !IsAdmin(u).Result)
                .Select(u => new { u.Id , u.UserName});

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddAdminModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Users = (await dbContext.Users
                    .AsNoTracking()
                    .ToListAsync())
                    .Where(u => !IsAdmin(u).Result)
                    .Select(u => new { u.Id, u.UserName });

                return View();
            }

            var user = dbContext.Users.FirstOrDefault(u => u.Id == model.Id);
            await userManager.AddToRoleAsync(user, "Administrator");

            return Redirect("~/Admin/");
        }
    }
}

LicenseManager.Server/Controllers/LicenseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LicenseManager.Server.Areas.Identity.Data;
using LicenseManager.Server.Data;
using LicenseManager.Server.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Syncfusion.EJ2.Base;

namespace LicenseManager.Server.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class LicenseController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public LicenseController(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> UrlDatasource([FromBody] DataManagerRequest dm)
        {
            var licensesList = await dbContext.Licenses
                .AsNoTracking()
                .Include(l => l.Product)
                .Include(l => l.User)
                .ToListAsync();

            var gridObjects = licensesList
                .Select(license => new
                {
                    license.Id,
                    license.Key,
                    license.Hwid,
                    license.Active,
                    Product = license.Product.Name,
                    User = license.User?.UserName,
                    license.RedeemDate,
                    license.CreationDate
                });

            return this.PerformGridOerations(gridObjects, dm);
        }

        public async Task<IActionResult> Update([FromBody] CRUDModel<dynamic> crud)
        {
            string key = crud.Value.Key.ToString();

            var license = await dbContext.Licenses.FindAsync(int.Parse(crud.Key.ToString()));
            var existingLicense = await dbContext.Licenses.FirstOrDefaultAsync(l => l.Key == key);

            if (existingLicense != null && existingLicense.Id != license.Id)
            {
                return StatusCode(400, "Update failed, license with this Key already exists!");
            }

            license.Key = crud.Value.Key;
            license.Hwid = crud.Value.Hwid;
            license.Active = crud.Value.Active;

            await dbContext.SaveChangesAsync();

            return Json(crud.Value);
        }

        public async Task<IActionResult> Delete([FromBody] CRUDModel<ApplicationLicense> crud)
        {            
            var license = await dbContext.Licenses.FindAsync(int.Parse(crud.Key.ToString()));

            dbContext.Remove(license);
            await dbContext.SaveChangesAsync();

            return Json(crud.Value);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            ViewBag.Products = await dbContext.Products
                .AsNoTracking()
                .ToListAsync();

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddLicenseModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Products = await dbContext.Products
                    .AsNoTracking()
                    .ToListAsync();

                return View();
            }

            var product = dbContext.Products.Find(model.Id);

            if (product == null)
            {
                ModelState.AddModelError("", "Selected product not longer exists.");

                ViewBag.Products = await dbContext.Products
                    .AsNoTracking()
                    .ToListAsync();

                return View();
            }

            for (int i = 0; i < model.Count; i++)
            {
                var license = new ApplicationLicense
                {
                    Key = Guid.NewGuid().ToString(),
                    Product = product
                };

                await dbContext.AddAsync(license);
            }

            await dbContext.SaveChangesAsync();

            return Redirect("~/License/");
        }
    }
}

LicenseManager.Server/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LicenseManager.Server.Areas.Identity.Data;
using LicenseManager.Server.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Syncfusion.EJ2.Base;
using Utf8Json.Formatters;

namespace LicenseManager.Server.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public ProductController(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> UrlDatasource([FromBody] DataManagerRequest dm)
        {
            var productsList = await dbContext.Products
                .AsNoTracking()
                .Include(p => p.Licenses)
                .ToListAsync();

            var gridObjects = productsList
                .Select(product => new
                {
                    product.Id,
                    product.Name,
                    product.Description,
                    product.Suspended,
                    Keys = product.Licenses.Count,
                    product.CreationDate
                });

            return this.PerformGridOerations(gridObjects, dm);
        }

        public async Task<IActionResult> Insert([FromBody] CRUDModel<ApplicationProduct> crud)
        {
            var product = new ApplicationProduct
            {
                Name = crud.Value.Name,
                Description = crud.Value.Description,
                Suspended = crud.Value.Suspended
            };

            if (await dbContext.Products.FirstOrDefaultAsync(p => p.Name == product.Name) != null)
            {
                return StatusCode(400, "Insert failed, product with this name already exists!");
            }

            await dbContext.AddAsync(product);
            await dbContext.SaveChangesAsync();

            return Json(crud.Value);
        }

        public async Task<IActionResult> Update([FromBody] CRUDModel<ApplicationProduct> crud)
        {
            var product = await dbContext.Products.FindAsync(crud.Value.Id);
            var existingProduct = await dbContext.Products.FirstOrDefaultAsync(p => p.Name == crud.Value.Name);

            if (existingProduct != null && existingProduct.Id != product.Id)
            {
                return StatusCode(400, "Update failed, product with this name already exists!");
            }

            product.Name = crud.Value.Name;
            product.Description = crud.Value.Description;
            product.Suspended = crud.Value.Suspended;

            await dbContext.SaveChangesAsync();

            return Json(crud.Value);
        }

        public async Task<IActionResult> Delete([FromBody] CRUDModel<ApplicationProduct> crud)
        {
            var product = await dbContext.Products.FindAsync(int.Parse(crud.Key.ToString()));

            dbContext.Remove(product);
            await dbContext.SaveChangesAsync();

            return Json(crud.Value);
        }
    }
}

LicenseManager.Server/Controllers/UserController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LicenseManager.Server.Areas.Identity.Data;
using LicenseManager.Server.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Syncfusion.EJ2.Base;

namespace LicenseManager.Server.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext dbContext;
        private readonly UserManager<ApplicationUser> userManager;

        public UserController(ApplicationDbContext dbContext, UserManager<ApplicationUser> userManager)
        {
            this.dbContext = dbContext;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> UrlDatasource([FromBody] DataManagerRequest dm)
        {
            var usersList = await dbContext.Users
                .AsNoTracking()
                .Include(u => u.Licenses)
                .ToListAsync();

            var gridObjects = usersList
                .Select(user => new
                {
                    user.Id,
                    user.UserName,
                    user.Email,
                    user.LockoutEnd,
                    Keys = user.Licenses.Count,
                    user.RegisterDate
                });

            return this.PerformGridOerations(gridObjects, dm);
        }

        public async Task<IActionResult> Update([FromBody] CRUDModel<ApplicationUser> crud)
        {
            var user = await userManager.FindByIdAsync(crud.Value.Id);
            var existingUsername = await userManager.FindByNameAsync(crud.Value.UserName);
            var existingEmail = await userManager.FindByNameAsync(crud.Value.Email);

            string error = string.Empty;

            if (existingUsername != null && existingUsername.Id != user.Id)
            {
                error += "User with this Username already exists!";
            }

            if (existingEmail != null && existingEmail.Id != user.Id)
            {
                if (error != string.Empty)
                {
                    error += " ";
                }

                error += "User with this Email already exists!";
            }

            if (error != string.Empty)
            {
                return StatusCode(400, error);
            }

            user.UserName = crud.Value.UserName;
            user.Email = crud.Value.Email;
            user.LockoutEnd = crud.Value.LockoutEnd;

            await userManager.UpdateAsync(user);

            return Json(crud.Value);
        }

        public async Task<IActionResult> Delete([FromBody] CRUDModel<ApplicationUser> crud)
        {
            var user = await userManager.FindByIdAsync(crud.Key.ToString());

            if (await userManager.IsInRoleAsync(user, "SuperAdmin"))
            {
                return StatusCode(400, "SuperAdmin cannot be deleted.");
            }

            await userManager.DeleteAsync(user);

            return Json(crud.Value);
        }
    }
}

LicenseManager.Server/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using LicenseManager.Server.Areas.Identity.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LicenseManager.Server</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/ej2/bootstrap4.css" />
    <script src="~/js/ej2/ej2.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LicenseManager.Server</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Administrator"))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="License" asp-action="Index">Licenses</a>
                        </li>
                        }
                        @if(SignInManager.IsSignedIn(User) && User.IsInRole("SuperAdmin"))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admins</a>
                        </li>
                        }
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year Michał Guźlewski - LicenseManager.Server
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <ejs-scripts></ejs-scripts>
    @RenderSection("Scripts", required: false)

</body>
</html>